# Generated by Django 2.2.10 on 2020-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salespersonTrackerREST", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="Phone_no",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesperson",
            name="Phone_no",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
