# Generated by Django 2.2.10 on 2020-03-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salespersonTrackerRest', '0003_auto_20200306_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Salesperson_Ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Salesperson'),
        ),
        migrations.AlterField(
            model_name='dailytarget',
            name='Assigned_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_Code',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='Assigned_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='Assigned_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Salesperson'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Managed_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
    ]
