# Generated by Django 2.2.10 on 2020-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespersonTrackerREST', '0003_auto_20200317_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Photo',
            field=models.ImageField(default='media/Default.png', upload_to='managers'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Photo',
            field=models.ImageField(default='media/Default.png', upload_to='salesperson'),
        ),
    ]
