# Generated by Django 2.2.10 on 2020-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salespersonTrackerREST", "0004_auto_20200317_2301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="Photo",
            field=models.ImageField(default="Default.png", upload_to="managers"),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="Photo",
            field=models.ImageField(default="Default.png", upload_to="salesperson"),
        ),
    ]
