# Generated by Django 2.2.10 on 2020-03-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salespersonTrackerRest', '0005_auto_20200306_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Salesperson_Ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Salesperson'),
        ),
        migrations.AlterField(
            model_name='dailytarget',
            name='Assigned_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='Assigned_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='Assigned_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Salesperson'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Managed_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salespersonTrackerRest.Manager'),
        ),
    ]
