# Generated by Django 2.2.10 on 2020-03-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salespersonTrackerREST", "0007_auto_20200317_2308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytarget",
            name="Item_Ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="salespersonTrackerREST.Inventory",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="Photo",
            field=models.ImageField(upload_to="managers"),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="Photo",
            field=models.ImageField(upload_to="media/salesperson"),
        ),
    ]
