# Generated by Django 2.2.10 on 2020-03-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("salespersonTrackerREST", "0009_auto_20200318_0033")]

    operations = [
        migrations.RemoveField(model_name="dailytarget", name="Completed"),
        migrations.RemoveField(model_name="dailytarget", name="Quantity"),
    ]
