# Generated by Django 2.2.10 on 2020-04-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salespersonTrackerREST', '0011_salesperson_isloggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('Item_Group_Code', models.IntegerField()),
                ('Company_Item_code', models.IntegerField(primary_key=True, serialize=False)),
                ('Company_Code', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='Item')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='targetscompleted',
            name='User_ref',
        ),
        migrations.RemoveField(
            model_name='totaltargets',
            name='User_ref',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Item_Ref',
        ),
        migrations.AddField(
            model_name='bill',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='Target_ref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salespersonTrackerREST.DailyTarget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='item_ref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salespersonTrackerREST.Inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='Completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemassign',
            name='assign_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_Ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salespersonTrackerREST.warehouse'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='Item_Ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salespersonTrackerREST.warehouse'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='TargetsCompleted',
        ),
        migrations.DeleteModel(
            name='TotalTargets',
        ),
    ]
